name: GitStream workflow
on:
  pull_request:
    types: [opened, edited, synchronize]
  pull_request_review_comment:
    types: [created, edited]

jobs:
  gitstream:
    runs-on: ubuntu-latest
    name: GitStream workflow
    steps:
      - name: Evaluate Rules
        uses: linear-b/gitstream-github-action@v1
        with:
          rules-file: '.cm/gitstream.cm'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}