name: GitStream workflow

on:
  pull_request:
    types: [opened, edited, synchronize]
  pull_request_review_comment:
    types: [created, edited]

jobs:
  gitstream:
    runs-on: ubuntu-latest
    name: GitStream workflow
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch all branches
        run: git fetch --all

      - name: Evaluate Rules
        uses: linear-b/gitstream-github-action@v2
        with:
          rules_file: '.cm/gitstream.cm'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
